<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brand Lain_productCard__image</name>
   <tag></tag>
   <elementGuidId>b4c17803-a7fb-4b68-9c3c-f473a6ed5881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.productCard__image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94e7bc37-4024-4280-b4ea-f899b03437d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg</value>
      <webElementGuid>7c9b4998-f146-4f73-a333-ab9a71c78b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productCard__image</value>
      <webElementGuid>85d9d874-6489-4226-817f-b5ea609c81b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg</value>
      <webElementGuid>54bea974-33c5-4460-8e6e-76f68076ca0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>9b76f9ab-428c-4ba8-be06-851bd4a49887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appSection&quot;]/div[@class=&quot;productItems&quot;]/div[@class=&quot;productItems__row&quot;]/div[@class=&quot;productItems__cell&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;productCard__head&quot;]/div[@class=&quot;productCard__imageHolder&quot;]/a[1]/img[@class=&quot;productCard__image&quot;]</value>
      <webElementGuid>84ffae11-20ea-400c-82f1-f8bb0b7a33f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div/div/div/div/div/div/a/img</value>
      <webElementGuid>f443ca1a-e4ae-4adc-a4bf-377efebb2ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg')]</value>
      <webElementGuid>8a693078-46a9-4daa-8330-216a839447d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>b3b141a2-60aa-45c1-a7c5-2455f7796166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg']</value>
      <webElementGuid>413a7c95-5c32-4e39-9bc2-95c762cac0cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
