<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Brand Populer_categorySection__item__image</name>
   <tag></tag>
   <elementGuidId>2cbc080d-25ff-4d29-ab5a-ab7f603b290b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div[2]/div[2]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ef39720-7180-40b9-b6fb-aa50d3d4623a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>categorySection__item__image</value>
      <webElementGuid>6e0a877c-85ee-4e58-ab00-8edfceb9ddc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;categorySections scroll-y&quot;]/div[@class=&quot;categorySection&quot;]/div[@class=&quot;categorySection__body&quot;]/div[@class=&quot;categorySection__item&quot;]/a[@class=&quot;categorySection__item__anchor&quot;]/span[@class=&quot;categorySection__item__image&quot;]</value>
      <webElementGuid>952afb64-836e-4316-97ba-144a39c9c4a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div[2]/div[2]/div/a/span</value>
      <webElementGuid>5097c090-61ed-4de6-b6f7-5ede2ee0c048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a/span</value>
      <webElementGuid>ee3e3d19-27ff-4688-9ada-41d320d31db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
