<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifikasi_Nomor ini belum terdaftar sebagai reseller</name>
   <tag></tag>
   <elementGuidId>1d0b1852-8052-4f73-af6b-5da82431b710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/form/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7e215732-1d23-42c1-928a-cffc415149e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor ini belum terdaftar sebagai reseller</value>
      <webElementGuid>69f3d279-52ae-4f99-9518-61fffe0d81c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[1]/form[1]/p[1]</value>
      <webElementGuid>97a6e621-1ccc-43e2-a2a3-7258d057701c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/form/p</value>
      <webElementGuid>0aaac99b-f9b0-4365-9e71-c071067e2e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayo Masuk!'])[1]/following::p[2]</value>
      <webElementGuid>6fd86382-26f1-4588-8029-7e9d3c74e2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/preceding::p[1]</value>
      <webElementGuid>d5bcef69-4f53-4899-a16e-bec8edb13ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::p[1]</value>
      <webElementGuid>ef0bf9f4-15b3-4264-ad07-97e914b1ea5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor ini belum terdaftar sebagai reseller']/parent::*</value>
      <webElementGuid>e21cf3c9-6538-446f-ad23-5447c2032aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p</value>
      <webElementGuid>9c64d4d0-fbdb-472e-8369-137b82514b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Nomor ini belum terdaftar sebagai reseller' or . = 'Nomor ini belum terdaftar sebagai reseller')]</value>
      <webElementGuid>eede6e8e-9d4b-4feb-b63f-b7212a346dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
