<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brand Lain_productCard__image</name>
   <tag></tag>
   <elementGuidId>023d11c0-6c97-4086-812b-cbfbced554bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.productCard__image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cd1ae860-1518-47ec-b946-da22c7e77957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg</value>
      <webElementGuid>2c4ec4df-7fd4-462c-8a5a-44915b0142ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productCard__image</value>
      <webElementGuid>a0fafe90-cb7a-486e-8bef-8be69f7b5439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg</value>
      <webElementGuid>47275323-7cbc-458e-b84a-f982c970e889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>966ac82e-a9ba-44f0-82ca-89838db47be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appSection&quot;]/div[@class=&quot;productItems&quot;]/div[@class=&quot;productItems__row&quot;]/div[@class=&quot;productItems__cell&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;productCard__head&quot;]/div[@class=&quot;productCard__imageHolder&quot;]/a[1]/img[@class=&quot;productCard__image&quot;]</value>
      <webElementGuid>b0921d6e-9c54-40b3-8b3c-97b54efb8027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>586ba275-f908-47b9-af58-a589e463bf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg</value>
      <webElementGuid>ccde7fd2-9acc-464a-bf1b-d0ff519341a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productCard__image</value>
      <webElementGuid>3946a932-be64-4b87-99e7-07e832967c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg</value>
      <webElementGuid>3a1473af-0f32-406d-95f1-170a8f975579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>033a2858-ead3-47f7-b4d7-e29243eff80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appSection&quot;]/div[@class=&quot;productItems&quot;]/div[@class=&quot;productItems__row&quot;]/div[@class=&quot;productItems__cell&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;productCard__head&quot;]/div[@class=&quot;productCard__imageHolder&quot;]/a[1]/img[@class=&quot;productCard__image&quot;]</value>
      <webElementGuid>644b3aa8-99a3-4060-b607-e34397650a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div/div/div/div/div/div/a/img</value>
      <webElementGuid>a211645d-9d05-466a-a859-df57c360eeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg')]</value>
      <webElementGuid>287c2249-5e96-42bd-a1d2-d55cb59b1c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>a9881c36-e8dd-440b-82a5-f5ed9369450d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.evermos.com/public/small/q:100/evermos-production/brand/yumna/product/image/60d53a7fe61f4.jpg']</value>
      <webElementGuid>2adfc316-f7c8-407f-ad14-dc90d676b36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
