<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dsds_pickedAddressId</name>
   <tag></tag>
   <elementGuidId>e7f27e6d-d3a4-4c57-9ee2-80a12d4528a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='pickedAddressId'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a04a668-a0c5-489f-b908-471df90e719b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickedAddressId</value>
      <webElementGuid>0f889cc7-6e3e-4bf6-8039-7182b62aafd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>55c9d8c0-2b2b-42a1-b99f-9e8686ac56bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100001113737</value>
      <webElementGuid>5c8bff79-adb2-489c-a2e6-56cf9631d635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;modalDrawer&quot;]/div[@class=&quot;modalDrawer__panel&quot;]/div[@class=&quot;modalDrawer__wrapper&quot;]/div[@class=&quot;modalDrawer__wrapper&quot;]/div[2]/div[@class=&quot;addressLists scroll-y&quot;]/label[@class=&quot;addressList&quot;]/div[@class=&quot;addressList__head&quot;]/input[1]</value>
      <webElementGuid>1e1a317e-63f6-47b3-aea3-a071bc30476a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='pickedAddressId'])[2]</value>
      <webElementGuid>afaba6cb-4e47-413b-b1a0-3e5e57b7c1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div/div[2]/div/div[2]/div/label[2]/div/input</value>
      <webElementGuid>6682110b-ab88-4773-9209-15742584f35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/input</value>
      <webElementGuid>701ea219-8c0b-48c3-a28e-d939ecef520a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pickedAddressId' and @type = 'radio']</value>
      <webElementGuid>807bebbb-e498-4281-898f-25e88495f7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
