<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rumahsinggah123123</name>
   <tag></tag>
   <elementGuidId>9a5ccd42-376e-4b68-9c63-90519813f9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[5]/div/div[2]/div/div[2]/div/label[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3eaf4bd9-a18a-47cf-96c5-c74368d4dbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addressList__title</value>
      <webElementGuid>c9cb097a-86a3-4d4a-9201-30e75c8d39b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rumahsinggah123123</value>
      <webElementGuid>e4084a39-d2bd-4bfb-a3c9-16123a694590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;modalDrawer&quot;]/div[@class=&quot;modalDrawer__panel&quot;]/div[@class=&quot;modalDrawer__wrapper&quot;]/div[@class=&quot;modalDrawer__wrapper&quot;]/div[2]/div[@class=&quot;addressLists scroll-y&quot;]/label[@class=&quot;addressList&quot;]/div[@class=&quot;addressList__head&quot;]/span[@class=&quot;addressList__title&quot;]</value>
      <webElementGuid>13d18cbb-bd3a-4013-9c70-497c4c4af056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div/div[2]/div/div[2]/div/label[2]/div/span</value>
      <webElementGuid>31a72db8-9cb7-47da-8ddc-c78176519907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dsds'])[1]/following::span[1]</value>
      <webElementGuid>ee8310f1-d641-42d7-938a-9d5f360fb713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Alamat Pengiriman'])[1]/following::span[3]</value>
      <webElementGuid>8763147c-0933-4e5f-9b4c-bcf5ed7e7f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='❤️ Sha ❤️'])[1]/preceding::span[1]</value>
      <webElementGuid>de0e4f1d-3eb0-4e0e-af01-ad573d6a1934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('(대한민국) 서울특별시 종로구 사직로3길 23, 102동 304호 홍길동 귀하 30174. !', '&quot;', '', '&quot;', '')])[1]/preceding::span[2]</value>
      <webElementGuid>ae42f0e9-fedd-4377-a75d-fe0d3e86ae4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rumahsinggah123123']/parent::*</value>
      <webElementGuid>4af33707-2a02-420d-a06c-85b65d8d7278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/span</value>
      <webElementGuid>8815d6fc-fd6a-4aac-a359-680a7ea339a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rumahsinggah123123' or . = 'Rumahsinggah123123')]</value>
      <webElementGuid>3ee88435-c0a0-4ee1-a320-0ee689c0e9d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
